python3 parser.py "(C / {A + {D/E}} )-I" "8.svg"
python3 parser.py "({A + {D/E}} / C)-I" "7.svg"
python3 parser.py "(A^B_DC^D/E^F_G+H)-I" "1.svg"
python3 parser.py "(A_{D_{D_{D_{D_{D_{D_{D}}}}}}}^{D^{D^{D^{D^{D^{D}}}}}})" "2.svg"
python3 parser.py "(D)" "3.svg"
python3 parser.py "(A/B/C/D)" "4.svg"
python3 parser.py "(E^E_E)" "5.svg"
python3 parser.py "(E_E^E)" "6.svg"